
### get all users
GET http://localhost:2000/api/user

### Get one user
GET http://localhost:2000/api/user/5yCQVk

### save user
POST http://localhost:2000/api/user
Content-Type: application/json

{
  "name": "Carlo",
  "lastname": "Par",
  "email": "c.par@gmail.com"
}

### Delete a user by id
DELETE http://localhost:2000/api/user/_lJmOM

### Update a user by id
PATCH http://localhost:2000/api/user/Sc0Mk8
Content-Type: application/json

{
  "email": "c.parra@gmail.com"
}

### save a url
POST http://localhost:2000/api/url/Sc0Mk8
content-type: application/json

{
  "link": "http://www.si.com"
}

### get one url
GET http://localhost:2000/api/url/Sc0Mk8

### get all articles
GET http://localhost:2000/api/article

### save a article
POST http://localhost:2000/api/article

Content-Type: application/json

{
  "name": "portatil",
  "price": "200",
  "description": "portatil de escritorio",
  "image": "http://www.si.com/portatil.jpg"
}

### get one article
GET http://localhost:2000/api/article/123456

### edit an article
PATCH http://localhost:2000/api/article/123456
Content-Type: application/json

{
  "name": "portatil",
  "price": "200",
  "description": "portatil de escritorio",
  "image": "http://www.si.com/portatil.jpg"
}

### 404 error
GET http://localhost:2000/api/ruta/no/existe