
### get all users
GET http://localhost:2000/api/user

### Get one user
GET http://localhost:2000/api/user/EZK6Mv

### save user
POST http://localhost:2000/api/user/signup
Content-Type: application/json

{
  "name": "pruebita",
  "lastname": "prueba",
  "email": "prueba@gmail.com",
  "password": "12345678"
}

### Login
POST http://localhost:2000/api/user/login
Content-Type: application/json

{
  "email": "prueba@gmail.com",
  "password": "7Gmi1K7hRJRgCM7x2qIxn40szz2U9h"
}

### Delete a user by id
DELETE http://localhost:2000/api/user/gUVA9m

### Update a user by id
PATCH http://localhost:2000/api/user/Sc0Mk8
Content-Type: application/json

{
  "email": "c.parra.edit@gmail.com"
}

### save a url
POST http://localhost:2000/api/url/630bca80a854af68b42fdc38
content-type: application/json

{
  "link": "http://www.si.com"
}

### get one url
GET http://localhost:2000/api/url/Sc0Mk8

### get all articles
GET http://localhost:2000/api/article

### save a article
POST http://localhost:2000/api/article

Content-Type: application/json

{
  "name": "portatil",
  "price": "200",
  "description": "portatil de escritorio",
  "image": "http://www.si.com/portatil.jpg"
}

### get one article
GET http://localhost:2000/api/article/123456

### edit an article
PATCH http://localhost:2000/api/article/123456
Content-Type: application/json

{
  "name": "portatil",
  "price": "200",
  "description": "portatil de escritorio",
  "image": "http://www.si.com/portatil.jpg"
}


### Create role
POST http://localhost:2000/api/role
Content-Type: application/json

{
  "id": "1",
  "name": "admin"
}

### Get a role
GET http://localhost:2000/api/role/1

### 404 error
GET http://localhost:2000/api/ruta/no/existe