name: Lint the code

on: push

jobs:
  test:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Node.js dependecies
        run: npm ci

      - name: Revert changes in the package-lock.json file if they exist
        run: git restore package-lock.json

      - name: Lint Action
        uses: wearerequired/lint-action@v2.1.0
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true


